# N<span style="color: #99ffff;">-</span>AND ITALIA <span style="color: #99ffff;">-</span> ADEBANJI ADELOWO

## Working with the DataBase: VENPAYBI

### The Table MpayMerchantsInstantKpis

In [1]:
import os
import sys
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pyodbc
pyodbc.drivers()

['SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'SQL Server Native Client RDA 11.0',
 'ODBC Driver 17 for SQL Server']

First establish connection to the database using python

In [3]:
import pandas as pd
import matplotlib.pyplot as plt


# server = 'localhost\sqlexpress' # for a named instance
# server = 'myserver,port' # to specify an alternate port
server = 'vpay-asdmi.public.21203d2a181c.database.windows.net,3342' 
database = 'VENPAY-BI' 
username = 'nandaa' 
password = 'Timileyin1998'  

engine = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = engine.cursor()

In [ ]:
query = """
      SELECT *
  FROM [VENPAY-BI].[dbo].[MpayMerchantsInstantKpis]
 
 """

df_mpay = pd.read_sql(query, engine)
df_mpay

In [ ]:
df_mpay.describe()

,PK_MpayMerchantsDailyKpiId,EK_MerchantId,ActiveUsersCounter,ActiveStickersCounter,TotalStickersCounter,TotalTransactionsCounter,WalletsTransactionsCounter,CardsTransactionsCounter,ExtUserIdTransactionsCounter,TotalRechargesCounter,...,WalletsSelectionsCounter,CardsSelectionsCounter,TotalTransactionsValue,WalletsTransactionsValue,CardsTransactionsValues,ExtUserIdTransactionsValue,TotalRechargesValue,CardsRechargesValue,CashRechargesValue,TotalWalletsBalance
count,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,...,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06,4.306878e+06
mean,2.153440e+06,5.415707e+01,7.636068e+00,7.667028e+00,1.671226e+03,7.089188e+00,6.855547e+00,2.094025e-01,2.423821e-02,2.780529e+01,...,8.876283e+00,2.003660e-01,4.982369e+03,4.839071e+03,1.304838e+02,1.281358e+01,1.638569e+05,1.623130e+05,1.543900e+03,1.056910e+09
std,1.243289e+06,2.941175e+01,7.705248e+01,7.613832e+01,9.927102e+03,7.104951e+01,6.882902e+01,2.171224e+00,3.412235e-01,3.447021e+01,...,9.201627e+01,2.070827e+00,4.997916e+04,4.865335e+04,1.328993e+03,1.852065e+02,1.956089e+05,1.932691e+05,1.641123e+04,7.108773e+07
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.600000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.290938e+08
25%,1.076720e+06,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+04,3.000000e+04,0.000000e+00,9.974723e+08
50%,2.153440e+06,5.400000e+01,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.500000e+04,6.500000e+04,0.000000e+00,1.059216e+09
75%,3.230159e+06,7.800000e+01,0.000000e+00,0.000000e+00,6.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.300000e+01,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.550000e+05,2.550000e+05,0.000000e+00,1.117889e+09
max,4.306878e+06,1.130000e+02,4.260000e+03,3.498000e+03,8.689900e+04,3.781000e+03,3.643000e+03,1.760000e+02,1.800000e+01,6.420000e+02,...,5.201000e+03,1.710000e+02,3.494400e+06,3.370050e+06,1.243500e+05,1.010000e+04,2.497550e+06,2.160000e+06,1.946520e+06,1.183337e+09